insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('Veal - Liver', 45.28, 85, 'Edgetag');
insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('Wine - Casablanca Valley', 52.06, 62, 'Realcube');
insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('Peach - Halves', 14.46, 41, 'Kare');
insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('Pasta - Canelloni, Single Serve', 77.27, 73, 'Babbleset');
insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('Banana - Green', 88.83, 56, 'Oodoo');
insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('The Pop Shoppe - Grape', 8.16, 24, 'Izio');
insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('Oil - Hazelnut', 80.68, 21, 'Thoughtworks');
insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('Juice - Apple 284ml', 46.2, 52, 'Fiveclub');
insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('Rabbit - Saddles', 4.99, 23, 'Meedoo');
insert into produto (nome_produto, preco_produto, estoque, nome_empresa) values ('Bread - Flat Bread', 17.21, 69, 'Feednation');
