insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Vermont', 'Muḩammad Āghah Wuluswālī', null, 1);
insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Oxford', 'Tsowkêy', null, 2);
insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Kipling', 'Dowr-e Rabāţ', null, 3);
insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Gale', 'Chowṉêy', null, 4);
insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Jenna', 'Qarah Bāgh Bāzār', null, 5);
insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Prentice', 'Kanḏay', null, 6);
insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Canary', 'Khulm', null, 7);
insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Dorton', 'Kafir Qala', null, 8);
insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Comanche', 'Larkird', null, 9);
insert into endereco (bairro, rua, cidade, cep, id_estado) values ('Afghanistan', 'Thompson', '’Unābah', null, 10);
