-- MySQL Script generated by MySQL Workbench
-- Thu Sep 22 16:50:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `ibge` INT(2) NULL DEFAULT NULL,
  `pais` INT(3) NULL DEFAULT NULL,
  `ddd` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8
COMMENT = 'Unidades Federativas';


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `rua` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `idEstado` INT(11) NULL DEFAULT NULL,
  `cep` VARCHAR(45) NULL DEFAULT NULL,
  `data_de_nasc` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idEstado` (`idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_idEstado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `mydb`.`estados` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `nome` VARCHAR(200) NOT NULL,
  `localizacao` VARCHAR(400) NULL DEFAULT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `codigoProduto` INT(11) NOT NULL,
  `nome` VARCHAR(200) NULL DEFAULT NULL,
  `precoProduto` FLOAT NOT NULL,
  `quant_no_estoque` INT(11) NOT NULL,
  `Fornecedor_nome` VARCHAR(200) NOT NULL,
  `statusProduto` TINYINT NULL,
  PRIMARY KEY (`codigoProduto`, `Fornecedor_nome`),
  INDEX `fk_Produto_Fornecedor_idx` (`Fornecedor_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_nome`)
    REFERENCES `mydb`.`fornecedor` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `login` VARCHAR(30) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `permissao` TINYINT(4) NULL DEFAULT NULL,
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `data_de_nascUsuario` DATE NULL DEFAULT NULL,
  `cpfUsuario` VARCHAR(16) NULL DEFAULT NULL,
  `idade` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `codigoVenda` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `comissaoVendedor` FLOAT NULL DEFAULT NULL,
  `lucro` FLOAT NOT NULL,
  `idCliente` INT(11) NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`codigoVenda`),
  INDEX `fk_Venda_idCliente` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Venda_idUsuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`id`),
  CONSTRAINT `fk_Venda_idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`vendaprodutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendaprodutos` (
  `Venda_codigoVenda` INT(11) NOT NULL,
  `quantidadeVendida` INT(11) NULL DEFAULT NULL,
  `produto_codigoProduto` INT(11) NOT NULL,
  `preco_produto` FLOAT NULL,
  PRIMARY KEY (`Venda_codigoVenda`, `produto_codigoProduto`),
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`Venda_codigoVenda` ASC) VISIBLE,
  INDEX `fk_vendaprodutos_produto1_idx` (`produto_codigoProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`Venda_codigoVenda`)
    REFERENCES `mydb`.`venda` (`codigoVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendaprodutos_produto1`
    FOREIGN KEY (`produto_codigoProduto`)
    REFERENCES `mydb`.`produto` (`codigoProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`historico_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigoProduto` INT NULL,
  `data` DATE NULL,
  `preco` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`produto_AFTER_INSERT` AFTER INSERT ON `produto` FOR EACH ROW
BEGIN
	insert into historico_produto values (null, codigoProduto, now(), new.precoProduto);
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`produto_AFTER_UPDATE` AFTER UPDATE ON `produto` FOR EACH ROW
BEGIN
	if new.precoProduto <> old.precoProduto and new.statusProduto=1 then
		insert into historico_produto values (null, codigoProduto, now(), new.precoProduto);
	end if;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
