-- MySQL Script generated by MySQL Workbench
-- Sat Sep 24 18:29:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `ibge` INT(2) NULL DEFAULT NULL,
  `pais` INT(3) NULL DEFAULT NULL,
  `ddd` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8
COMMENT = 'Unidades Federativas';


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `id_estado` INT(11) NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_estados1_idx` (`id_estado` ASC) ,
  CONSTRAINT `fk_endereco_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `mydb`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `data_de_nasc` DATE NULL DEFAULT NULL,
  `id_endereco` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_endereco1_idx` (`id_endereco` ASC),
  CONSTRAINT `fk_cliente_endereco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `mydb`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `nome_empresa` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL,
  `id_endereco` INT NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome_empresa`, `cnpj`),
  INDEX `fk_fornecedor_endereco1_idx` (`id_endereco` ASC),
  CONSTRAINT `fk_fornecedor_endereco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `mydb`.`endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id_produto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(200) NOT NULL,
  `preco_produto` FLOAT NOT NULL,
  `estoque` INT(11) NOT NULL,
  `nome_empresa` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(30) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `cpf` VARCHAR(16) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `idade` INT(11) NULL DEFAULT NULL,
  `permissao` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id_venda` INT(11) NOT NULL AUTO_INCREMENT,
  `data_venda` DATE NOT NULL,
  `comissao_vendedor` FLOAT NULL DEFAULT NULL,
  `lucro` FLOAT NOT NULL,
  `id_cliente` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_Venda_idCliente` (`id_cliente` ASC) ,
  INDEX `fk_Venda_idUsuario` (`id_usuario` ASC),
  CONSTRAINT `fk_Venda_idCliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Venda_idUsuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`historico_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico_produto` (
  `id_historico_produto` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `data_atualizacao` DATE NULL,
  `preco_novo` FLOAT NULL,
  `preco_antigo` FLOAT NULL,
  `nome_empresa` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_historico_produto`),
  INDEX `fk_historico_produto_fornecedor1_idx` (`nome_empresa` ASC),
  CONSTRAINT `fk_historico_produto_fornecedor1`
    FOREIGN KEY (`nome_empresa`)
    REFERENCES `mydb`.`fornecedor` (`nome_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda_produtos` (
  `id_venda` INT(11) NOT NULL,
  `quantidade_produto` INT(11) NOT NULL,
  `id_historico_produto` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`id_venda` ASC),
  INDEX `fk_vendaprodutos_historico_produto1_idx` (`id_historico_produto` ASC),
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`id_venda`)
    REFERENCES `mydb`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendaprodutos_historico_produto1`
    FOREIGN KEY (`id_historico_produto`)
    REFERENCES `mydb`.`historico_produto` (`id_historico_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`produto_AFTER_INSERT` AFTER INSERT ON `produto` FOR EACH ROW
BEGIN
	insert into historico_produto values (null, id_produto, now(), new.preco_produto, new.preco_produto, new.nome_empresa);
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`produto_AFTER_UPDATE` AFTER UPDATE ON `produto` FOR EACH ROW
BEGIN
	if new.preco_produto <> old.preco_produto then
		insert into historico_produto values (null, id_produto, now(), new.preco_produto, old.preco_produto, new.nome_empresa);
	end if;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
