-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 11:03:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `nome` VARCHAR(200) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `data_de_nasc` DATE NOT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `codigoVenda` INT NOT NULL,
  `data` DATE NOT NULL,
  `comissaoVendedor` DECIMAL(1000) NULL,
  `lucro` DECIMAL(10000) NOT NULL,
  `Cliente_nome` VARCHAR(200) NOT NULL,
  `vendedorNome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigoVenda`, `Cliente_nome`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_nome` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_nome`)
    REFERENCES `mydb`.`Cliente` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `nome` VARCHAR(200) NULL,
  `localizacao` VARCHAR(400) NULL,
  `telefone` VARCHAR(30) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `codigoProduto` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `precoProduto` DECIMAL(1000) NOT NULL,
  `quant_no_estoque` INT NOT NULL,
  `Fornecedor_nome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigoProduto`, `Fornecedor_nome`),
  INDEX `fk_Produto_Fornecedor_idx` (`Fornecedor_nome` ASC),
  CONSTRAINT `fk_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_nome`)
    REFERENCES `mydb`.`Fornecedor` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `login` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `permissao` TINYINT NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VendaProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VendaProdutos` (
  `Venda_codigoVenda` INT NOT NULL,
  `Produto_codigoProduto` INT NOT NULL,
  `quantidadeVendida` INT NULL,
  PRIMARY KEY (`Venda_codigoVenda`, `Produto_codigoProduto`),
  INDEX `fk_Venda_has_Produto_Produto1_idx` (`Produto_codigoProduto` ASC),
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`Venda_codigoVenda` ASC),
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`Venda_codigoVenda`)
    REFERENCES `mydb`.`Venda` (`codigoVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Produto_Produto1`
    FOREIGN KEY (`Produto_codigoProduto`)
    REFERENCES `mydb`.`Produto` (`codigoProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
