-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 11:03:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `nome` VARCHAR(200) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `data_de_nasc` DATE NOT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `codigoVenda` INT NOT NULL,
  `data` DATE NOT NULL,
  `comissaoVendedor` DECIMAL(1000) NULL,
  `lucro` DECIMAL(10000) NOT NULL,
  `Cliente_nome` VARCHAR(200) NOT NULL,
  `vendedorNome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigoVenda`, `Cliente_nome`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_nome` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_nome`)
    REFERENCES `mydb`.`Cliente` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `nome` VARCHAR(200) NULL,
  `localizacao` VARCHAR(400) NULL,
  `telefone` VARCHAR(30) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `codigoProduto` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `precoProduto` DECIMAL(1000) NOT NULL,
  `quant_no_estoque` INT NOT NULL,
  `Fornecedor_nome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigoProduto`, `Fornecedor_nome`),
  INDEX `fk_Produto_Fornecedor_idx` (`Fornecedor_nome` ASC),
  CONSTRAINT `fk_Produto_Fornecedor`
    FOREIGN KEY (`Fornecedor_nome`)
    REFERENCES `mydb`.`Fornecedor` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `login` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `permissao` TINYINT NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VendaProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VendaProdutos` (
  `Venda_codigoVenda` INT NOT NULL,
  `Produto_codigoProduto` INT NOT NULL,
  `quantidadeVendida` INT NULL,
  PRIMARY KEY (`Venda_codigoVenda`, `Produto_codigoProduto`),
  INDEX `fk_Venda_has_Produto_Produto1_idx` (`Produto_codigoProduto` ASC),
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`Venda_codigoVenda` ASC),
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`Venda_codigoVenda`)
    REFERENCES `mydb`.`Venda` (`codigoVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Produto_Produto1`
    FOREIGN KEY (`Produto_codigoProduto`)
    REFERENCES `mydb`.`Produto` (`codigoProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE TABLE `estado` (
  `id` int(11) NOT NULL,
  `nome` varchar(75) DEFAULT NULL,
  `uf` varchar(2) DEFAULT NULL,
  `ibge` int(2) DEFAULT NULL,
  `pais` int(3) DEFAULT NULL,
  `ddd` varchar(50) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Unidades Federativas';

INSERT INTO `estado` (`id`, `nome`, `uf`, `ibge`, `pais`, `ddd`) VALUES
(1, 'Acre', 'AC', 12, 1, '68'),
(2, 'Alagoas', 'AL', 27, 1, '82'),
(3, 'Amazonas', 'AM', 13, 1, '97,92'),
(4, 'Amapá', 'AP', 16, 1, '96'),
(5, 'Bahia', 'BA', 29, 1, '77,75,73,74,71'),
(6, 'Ceará', 'CE', 23, 1, '88,85'),
(7, 'Distrito Federal', 'DF', 53, 1, '61'),
(8, 'Espírito Santo', 'ES', 32, 1, '28,27'),
(9, 'Goiás', 'GO', 52, 1, '62,64,61'),
(10, 'Maranhão', 'MA', 21, 1, '99,98'),
(11, 'Minas Gerais', 'MG', 31, 1, '34,37,31,33,35,38,32'),
(12, 'Mato Grosso do Sul', 'MS', 50, 1, '67'),
(13, 'Mato Grosso', 'MT', 51, 1, '65,66'),
(14, 'Pará', 'PA', 15, 1, '91,94,93'),
(15, 'Paraíba', 'PB', 25, 1, '83'),
(16, 'Pernambuco', 'PE', 26, 1, '81,87'),
(17, 'Piauí', 'PI', 22, 1, '89,86'),
(18, 'Paraná', 'PR', 41, 1, '43,41,42,44,45,46'),
(19, 'Rio de Janeiro', 'RJ', 33, 1, '24,22,21'),
(20, 'Rio Grande do Norte', 'RN', 24, 1, '84'),
(21, 'Rondônia', 'RO', 11, 1, '69'),
(22, 'Roraima', 'RR', 14, 1, '95'),
(23, 'Rio Grande do Sul', 'RS', 43, 1, '53,54,55,51'),
(24, 'Santa Catarina', 'SC', 42, 1, '47,48,49'),
(25, 'Sergipe', 'SE', 28, 1, '79'),
(26, 'São Paulo', 'SP', 35, 1, '11,12,13,14,15,16,17,18,19'),
(27, 'Tocantins', 'TO', 17, 1, '63'),
(99, 'Exterior', 'EX', 99, NULL, NULL);

insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Robin Corstorphine', '157.8.146.35', 'rcorstorphine0@marriott.com', 'Água Verde', 'Service', 'Gongjiahe', '26453-456', 29/4/2021);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Corena Anderson', '81.111.177.110', 'canderson1@apache.org', 'Vorstadt', 'Knutson', 'Tiandiba', '13345-654', 24/3/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Marillin Dunne', '15.71.64.210', 'mdunne2@delicious.com', ' Ribeirão Fresco', 'Garrison', 'Náfplio', '23456-885', 2/1/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Atalanta Geertz', '108.219.97.72', 'ageertz3@liveinternet.ru', 'Garcia', 'Huxley', 'Bonao', '38754-532', 14/9/2021);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Cheslie Mawhinney', '196.117.146.208', 'cmawhinney4@foxnews.com', 'Da Glória', 'Mifflin', 'Turnišče', '65389-345', 28/4/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('West Powe', '48.35.200.144', 'wpowe5@youtu.be', 'Progresso', 'Pleasure', 'Meshcherino', '123-4327', 27/5/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Dalila Linster', '240.37.237.18', 'dlinster6@multiply.com', ' Bom Retiro', 'Division', 'Fort Macleod', '14123-541', 24/4/2021);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Arlena Vannuccinii', '239.96.151.113', 'avannuccinii7@51.la', 'Velha', 'Monument', 'Mauá', '12345-780', 6/3/2021);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Gianna Rentelll', '164.137.157.102', 'grentelll8@ameblo.jp', 'Velha Grande', 'Maywood', 'Krouna', '50234-654', 20/10/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Kellen O''Heffernan', '10.58.147.204', 'koheffernan9@google.ru', 'Passo Manso', 'Charing Cross', 'Qiujia', '12345-663', 13/5/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Loni Mathen', '41.190.175.210', 'lmathena@dot.gov', 'Salto Weissbach', 'Tomscot', 'Longwood', '12345-587', 23/11/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Hulda Ions', '31.84.32.104', 'hionsb@bloomberg.com', 'Do Salto', 'Summerview', 'Jiuxian', '23456-869', 29/11/2021);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Rochell de''-Ancy Willis', '213.159.87.215', 'rdeancyc@facebook.com', 'Escola Agrícola', 'Division', 'Toulouse', '66123-654', 28/4/2021);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Daile Targett', '99.6.242.161', 'dtargettd@gravatar.com', ' Água Verde', 'Boyd', 'Vermil', '08754-100', 23/10/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Denny O''Hanley', '132.255.184.224', 'dohanleye@home.pl', ' Vila Nova', 'Banding', 'Staromyshastovskaya', '43234-876', 9/1/2021);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Dulcinea Bloyes', '175.180.140.98', 'dbloyesf@jugem.jp', ' Itoupava Seca', 'Heath', 'Akron', '12309-777', 17/12/2021);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Sharia Prover', '198.14.9.133', 'sproverg@cnbc.com', 'Victor Konder', 'Hoard', 'Roldanillo', '35128-765', 21/6/2021);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Matty Cinderey', '199.120.139.121', 'mcindereyh@nhs.uk', ' Boa Vista', 'Nevada', 'Roi Et', '10854-369', 16/11/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Sibilla Moxsom', '27.245.99.100', 'smoxsomi@usa.gov', 'Ponta Aguda', 'Gina', 'Caucaguita', '42964-357', 19/1/2022);
insert into Cliente (nome, cpf, email, bairro, rua, cidade, cep, data_de_nasc) values ('Kathye Naughton', '167.6.134.190', 'knaughtonj@marketwatch.com', 'Nova Esperança', 'Killdeer', 'Sekirnik', '2212-534', 8/10/2022);